language: android
env:
  global:
  - ANDROID_API=26
  - ANDROID_BUILD_TOOLS=26.0.2
  - PROJECT_1=HelloToast
  - PROJECT_2=CounterHomework
  - PROJECT_3=ImplicitIntents
  - secure: TzVQ2ZpySC+cX4x8XXX0jtafksAiCk0Z5X/rKP6HNjmVeu+OqPVLcURrPUSNPckCd4fU1Uyd39HiF/nOM6KxL3a3msCb/itIv3fdVVzI7kgqq0QP1RG8bJqKP25BcLDXCMlOuXdcQ6Y4yTIk5kfKmJfOLcqz2q4Kj/E+ZiyVb2UKvsUkPUDfQ04bZnliAnuXZzwNtP2HQ5Vwuk7+5x6qUwTiFs0zG/lctX1CiGXHcM6SEvqSrkso810hOYvq9BgoCHVvDjOcypXu1liXSbtcaS1VMFU6+7fBFhgJNCxxER1VixfUaIHwGgicPnCD40sUe5r+W+1iEtvOdOyOHFmk12kAfUSkwrvZ+4RA4C0d3/JCj7Uee7GSawUOa46VMuy5n40CdpVkp6YIcLurxtGFhGvI42+GHYwPuk55Zn8QCT33iJci7Qo1/3lgFimUZ3fs0Uzd5K63Hbw/dTb2oFJ0MG/JMLNfrRdKqKm8/uT1qw2bJgqWR4PqRR+oxl57/643N5K0sEuzHpR/RR2VfkwvCWDch1wIfeoeLFx3vBDtThb0K86m7s95iHoGNPW/TiK3C8NL8ioM7MFkbpzFgpopZYi79cTHrgnOYFCABQFPwWme8TGRbOgH5/ICIRBGl2nttSTgV2Ew1xAWiCZYIiwEef6F96qfJZNOJTTipXsrCCU=
  - secure: LCO2wpD72n1ff1I87ARs9UmrG2PcXl+aX4ePTHcjszCHAepGQLCvSjLmRESJ/PJKQq8xMaIkIGKLmJbfczBkfhbZgJbUdZy0MaUskQb4l6onXMdc3B8IbBg6OioLr84yaYWfOdYbKjs2e+4CuA4E29S+XQsqh72GELd0zqgNCIE5QcVRrDhLGRhb0sY8FSC/CG4a2nbArQZYglksreylmiso34Lecvnj0BNisp0olrVlpTZWx39rLFYSAiUagy8foU8rclGgBXsDnh0ddinllt+2he86wACVZcTIiUOhz8/+TDtFZwLiuOCZP+mP95vYHhjrXS5YRJ45G7uYatT8CbPUnV1apoirxlS0Ndrpek1ri/ZtN0Qx5AMFc2vzUE/Lyzs3cMDlADy3RhAiOBhJt71LGFb27mO8s+D1YTDGwa+qkBrLgQTxNVxh8rwcbzDE5ng35CcgQiIXcmIb7i5hLBuLDdxClECaNYY0iIRw46kaFO8eDXoJ81fu3qPBt1g/oV/wk7lJ68i/vcUK2ctVvZdIWdkmiu07L2vTh/RkTMhJryDoi+zrOEZIIRgJf1O2uOpuSDv7JK5fj++HYaQ80W5WTLpo25B4cT/vXVlrouS4xy+WNqapg2z3f+RbG5xF2saNmm57Gq/UxfazuJD5ffQMfvQ7UpWmkXg++30F5Fs=
branches:
  only:
  - master
android:
  components:
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - extra-android-m2repository
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
before_install:
- export PROJECT_ROOT="${PWD}"
- chmod +x ${PROJECT_1}/gradlew
- chmod +x ${PROJECT_2}/gradlew
- chmod +x ${PROJECT_3}/gradlew
- chmod +x result_parser.py
before_script:
- adb kill-server
- adb connect ${EMULATOR_SERVER}
- adb devices
script:
- cd ${PROJECT_ROOT}
- cd ${PROJECT_1} && ./gradlew connectedDebugAndroidTest --stacktrace
- cd ${PROJECT_ROOT}
- cd ${PROJECT_2} && ./gradlew connectedDebugAndroidTest --stacktrace
- cd ${PROJECT_ROOT}
- cd ${PROJECT_3} && ./gradlew connectedDebugAndroidTest --stacktrace
after_script:
- cd ${PROJECT_ROOT}
- "./result_parser.py ${PROJECT_ROOT}/${PROJECT_1}/app/build/reports/androidTests/connected/com.example.android.hellotoast.IntentTest.html
  >> results.txt"
- "./result_parser.py ${PROJECT_ROOT}/${PROJECT_2}/app/build/reports/androidTests/connected/com.example.android.counterhomework.onSaveInstanceStateTest.html
  >> results.txt"
- "./result_parser.py ${PROJECT_ROOT}/${PROJECT_3}/app/build/reports/androidTests/connected/com.example.android.implicitintents.TakePictureTest.html
  >> results.txt"
- echo $(basename ${TRAVIS_REPO_SLUG}) ${TRAVIS_BRANCH} ${TRAVIS_COMMIT} $(git show
  -s --format=%ci ${TRAVIS_COMMIT} | cut -c 1-20) $(cat results.txt) > results.txt
- awk  '//{for(i=6;i<NF;i=i+2) print $i"\t"$(i+1)}' results.txt
- curl -d "@results.txt" -X POST ${DB_SERVER_URL}
